name: Continuous-Delivery

on:
  push:
    branches: [ master, developer ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Trigger production build
        run: npm run build:prod

      - name: Deploy build to Firebase Hosting
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
